# Generated by Django 2.1.4 on 2019-03-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subevent',
            name='title',
            field=models.CharField(blank=True, help_text='Optional specific event name (eg the lecture name within an event series)', max_length=255),
        ),
    ]
